### ISSUE TITLE
Could not run build

### ISSUE THREAD

**Issue by pi-ron** [ibloat/riot-redux-sample#1]
Hi There,

Just trying to install your package to have a play.  I'm coming unstuck on `npm run build` in particular `npm run build:js`

```
> browserify -d src/code/index.js -o dist/app.js

DEPRECATION WARNING: jade was renamed "pug" - the jade parser will be removed in riot@3.0.0!
TypeError: unknown: resolveModuleSource is not a function
    at File.resolveModuleSource (/Users/RoamingMac/Sites/riot-redux-sample/node_modules/babel-core/lib/transformation/file/index.js:343:39)
    at NodePath.enter (/Users/RoamingMac/Sites/riot-redux-sample/node_modules/babel-core/lib/transformation/modules/lib/metadata.js:29:42)
    at NodePath.call (/Users/RoamingMac/Sites/riot-redux-sample/node_modules/babel-core/lib/traversal/path/context.js:56:28)
    at NodePath.visit (/Users/RoamingMac/Sites/riot-redux-sample/node_modules/babel-core/lib/traversal/path/context.js:90:8)
    at TraversalContext.visitMultiple (/Users/RoamingMac/Sites/riot-redux-sample/node_modules/babel-core/lib/traversal/context.js:108:16)
    at TraversalContext.visit (/Users/RoamingMac/Sites/riot-redux-sample/node_modules/babel-core/lib/traversal/context.js:146:19)
    at Function.traverse.node (/Users/RoamingMac/Sites/riot-redux-sample/node_modules/babel-core/lib/traversal/index.js:76:17)
    at Object.traverse [as default] (/Users/RoamingMac/Sites/riot-redux-sample/node_modules/babel-core/lib/traversal/index.js:55:14)
    at NodePath.traverse (/Users/RoamingMac/Sites/riot-redux-sample/node_modules/babel-core/lib/traversal/path/index.js:163:23)
    at CommonJSFormatter.getMetadata (/Users/RoamingMac/Sites/riot-redux-sample/node_modules/babel-core/lib/transformation/modules/_default.js:129:22)
```

**Comment by ibloat** [comment]
Thank you for the heads-up!
I should have shrink-wrapped the dependencies.
This sample is getting a little bit long in the tooth anyway so I will wholesale redo it over the weekend.

**Comment by ibloat** [comment]
Switched to a rollup based build, using buble for transpiling.
Removed lots of noise, shrink-wrapped dependencies.

**Comment by ibloat** [comment]
Let me know if this is not working for you, closing for now

**Comment by pi-ron** [comment]
@ibloat thanks, that got it up and going.

So is riot-redux-mixin still recommended?  

I've done a bit of work 'manually' getting riot redux working together following [Andrew Van Slaars videos](https://www.youtube.com/watch?v=Y6vpKAGT2-8), and then [modified this guide](http://blog.krawaller.se/posts/a-react-redux-firebase-app-with-authentication/) for implementing Firebase w/redux to work with riot instead of react.

**Comment by ibloat** [comment]
We are using it in production on several projects in combination with redux-saga.
https://github.com/riot/riot/issues/1118 had quite a few solutions for integrating redux with riot but there doesn't seem to be a consensus on which is the 'correct' way to implement this, but the [riot-redux-mixin](https://github.com/ibloat/riot-redux-mixin) approach is working well for us and is getting some use elsewhere.
The repository itself does not have much activity because for our use cases it is pretty much feature complete.
Suggestions and/or pull requests are welcome though :+1: 
I am of course quite biased so take my endorsement with a pinch of salt!

**Comment by pi-ron** [comment]
Thanks @ibloat redux saga looks interesting.
